### ISSUE TITLE
Initial feedback and questions on the assignment

### ISSUE THREAD

**Issue by nets-qa** [raven123/AppiumWithRobot#1]
Hello Ravi Kumar,

Thank you for completing the assignment in a good quality and fast speed! There are several positive points we would like to highlight with you below:
- Clear and straight-forward instructions in the documentation
- Good framework design with the common reusable resource file pia-resources.robot
- Well organised the structure of project folders
- Well defined keywords and indicators

In addition, we would like to ask few questions:
- What are advantages of having modularisation of test cases and centralised resources? Is there any drawbacks of designing in such way?
- If we do need to support both iOS and Android in this assignment, what will you do to make the same test cases for iOS applications?
- What modifications needed in this project if we think to run the same test cases on multiple devices in parallel?

**Comment by raven123** [comment]
Hi, 
    Thanks for the feedback on the assignment @nets-qa . Please find below the response for the questions asked:

     A.  Advantages of modularization of test cases and centralized resources:

-  Reduction of code redundancy and utilization of same implementation in multiple test cases
- Centralized resources will ensure that you are making changes to the resources part without actually touching the test cases in case there is a change e.g locator changes or specific keyword flow change due to changes in functionality

     B.  Disadvantage of such structure : 

-  Team members should be aware of the new modular functions, keywords and other changes implemented within the team to avoid duplicate
-  As the code base will increase and mature in time, new team members might take some time to get familiar with the structure and way of writing test cases, keywords and configurations

    C. In order to make the same setup work for iOS and Android:
-	We can create an appium resource file which will help us pass on required capabilities for launching the tests on both
-	If the flow of the application is almost similar in both the platforms, we can just create separate resource files for storing locators specific to Android and iOS and call the specific one based on the platform we have to execute the test cases.In this way same test cases can be run on both platforms
-	If the flow is not similar on both platforms, it is better to have separate set of Test cases specific to each platforms as the complexity of maintaining the test cases will be much lesser in this approach

	D. In order to run the test cases in parallel on mutiple devices:
-	We would need 1 appium server for each device (using same appium server possible from appium 1.7 or greater but has performance issues in handling multiple devices) and configuring different serverPort for each device for adb calls
-	Use of pybot library to execute test cases in parallel. It can execute test cases in parallel at suite level as well as at test case level

**Comment by nets-qa** [comment]
Thanks for the detailed answers in depth! The answers sounds reasonable and clear! Appreciated all your collaboration in this code assignment and Rishi will inform you what we proceed in the next round!;)
